### ISSUE TITLE
Using micros() instead of millis(()

### ISSUE THREAD

**Issue by patrickvorgers** [MicroBeaut/Finite-State#2]
I was looking at the FSM implementation and saw that the timeouts use micros() which have a maximum duration of around 70 minutes. For my usecase I would like the timeout to be in the order of days (switching a pump - when not used for some time).
Why is micros() used instead of millis()? The timeout is specified in milliseconds so at first glance millis() could be used increasing the usefull timeout to around 49 days.

**Comment by MicroBeaut** [comment]
Time base calculation has been changed from `micros()` to `millis()`
